# Configuration documentation: https://docs.landscape.io/configuration.html
doc-warnings: yes
max-line-length: 80
ignore-paths:
    - demos
    - dev
    - docs
python-targets:
    - 2
    - 3
pyflakes:
    run: false