# Configuration documentation: https://docs.landscape.io/configuration.html
doc-warnings: yes
max-line-length: 80
ignore-paths:
    - demos/
    - dev/
    - docs/
    - pyupdater/_version.py
    - versioneer.py
python-targets:
    - 2
    - 3
pyflakes:
    run: false