language: python
sudo: false
cache: pip

matrix:
  include:
    - python: 2.7
      os: linux
      env: PYTHON=2.7
    - python: 3.3
      os: linux
      env: PYTHON=3.3
    - python: 3.4
      os: linux
      env: PYTHON=3.4
    - python: 3.5
      os: linux
      env: PYTHON=3.5
    - python: 3.6
      os: linux
      env: PYTHON=3.6
    - python: nightly
      os: linux
      env: PYTHON=nightly

    # Mac
    # - python: 2.7
    #   os: osx
    #   env: PYTHON=2.7
    # - python: 3.3
    #   os: osx
    #   env: PYTHON=3.3
    # - python: 3.4
    #   os: osx
    #   env: PYTHON=3.4
    # - python: 3.5
    #   os: osx
    #   env: PYTHON=3.5
    # - python: 3.6
    #   os: osx
    #   env: PYTHON=3.6
    # - python: nightly
    #   os: osx
    #   env: PYTHON=nightly

  allow_failures:
  - env: PYTHON=3.6
  - env: PYTHON=nightly
  # - os: osx

install:
- export PATH="/home/travis/.pyenv/bin:$PATH"
- eval "$(pyenv init -)"
- eval "$(pyenv virtualenv-init -)"
- curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
  | bash
- pip install tox-travis coveralls
- pip-accel install -r requirements.txt | cat
script:
- tox
after_success: coveralls
deploy:
  provider: pypi
  user: JohnyMoSwag
  password:
    secure: 0iX3mRqMP3iShjTznKzNKXvn5SyYy2QkKILUV+hp8/J3SeNU9PohvoNRTaJM9iFSdAbi6KUg0uivRaFOpc9ctK2bEXjPx8tHQ8KBZ6WBks9inIrcP+OnaQBYIvTU2oPtn4SCDpgBGTem7NhACbZV3Ls/A2NyFB6ly5xwzox3vKyfdcYjmAujDciHIq/fKQ1CNNq3/ImGgKZcvmvm2ugs1zsa/QDoOL+ykwVA8HMbCF8JYqf2gPpyrqwEfvoMCqCqM7sj4ySqAjWsIAPuCdTidZVFNDsA3I/fLmuUbQprk9Yc613zxMW19PkDw7nFxyPmwwi2qLRNssL+bJ6xeN8Rv6kIjNzbkmWr0hjEgGN1Ni64+amyqDCrVtNpGN+R3SWzM4LNdddes9CXN//EynC7QUwpKs7kdWxsRSa6Zl5Nv3zYmDSx5at96s2Uk3AhhlnNxc9oZQXkaWaM6C1jHlQ0dqhI6deYKJCc0LjreCwb5hvIhPw+2eQdKDbPa1sn+iNF0eTspLJkeoJZ8CRPCkj5Wqluu/vymjqg0IhDokhUpdjTsPPk5NEuv5O8qR54O63We0UpqRjAg25k2AhLSwBJbNhi2TDr34d5ZdHs2ZElYdWbGuHsUMjkxUPOxO4xOM2738I7nMblntXBta0z/c37W60IIGb6HxmwK8OFnBKP87s=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: JMSwag/PyUpdater
