site_name: PyUpdater
site_url: http://www.pyupdater.org
site_description: Pyinstaller Auto-Update Framework
google_analytics: ['UA-76455631-6', 'www.pyupdater.org']
pages:
- Home: index.md
- User Guide:
    - Installation: installation.md
    - Commands: commands.md
    - Usage: usage.md
    - Usage - Assets: usage-asset.md
    - Usage - Advanced: usage-advanced.md
    - Upgrading PyUpdater: upgrading.md
    - Create Upload Plugins: create_plugin.md
- Change Log: changelog.md
- Extras:
    - Data Folder Layout: data-folder-layout.md
    - Contributing: contributing.md
    - Downloads: downloads.md
    - License: license.md

theme: 'material'
repo_name: 'GitHub'
repo_url: 'https://github.com/JMSwag/PyUpdater'
extra:
  palette:
    primary: 'blue'
    accent: 'light blue'

dev_addr: 0.0.0.0:8080