site_name: PyUpdater
pages:
- Home: index.md
- User Guide:
    - Installation: installation.md
    - Commands: commands.md
    - Example Workflow: workflow.md
    - Upgrading PyUpdater: upgrading.md
    - Create Upload Plugins: create_plugin.md

- More Info:
    - Folder Layout: folder_structure.md
    - Contributing: contributing.md
    - Downloads: downloads.md
    - License: license.md
- Change Log: changelog.md

theme: 'material'
repo_name: 'GitHub'
repo_url: 'https://github.com/JMSwag/PyUpdater'
extra:
  palette:
    primary: 'blue'
    accent: 'light blue'

dev_addr: 0.0.0.0:8080